version: "3"
name: idn-prez4
services:
  prez4:
    image: "ghcr.io/rdflib/prez:${version}"
    restart: always
    ports:
      - 8000:8000
    environment:
      SPARQL_ENDPOINT: http://fuseki:3030/prez4
      SPARQL_USERNAME: $SPARQL_USERNAME
      SPARQL_PASSWORD: $SPARQL_PASSWORD
      ENABLE_SPARQL_ENDPOINT: true
      PREZ_TITLE: IDN Catalogue
      PROTOCOL: https
      CUSTOM_ENDPOINTS: true
      ENDPOINT_STRUCTURE: '["catalogs","collections","items","features"]'
      OTHER_PREDICATES: '["https://schema.org/color","https://schema.org/status"]'
      ORDER_LISTS_BY_LABEL: true
      SEARCH_METHOD: fts_fuseki
    networks:
      - network

networks:
  network:
    name: idn_network
    external: true