name: Deploys Prez API to Docker on VM

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/push_backend.yaml'
      - 'prez-compose.yaml'
      - 'prez_config/**'
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      version: 4.20.0
      SPARQL_USERNAME: ${{ secrets.SPARQL_USERNAME }}
      SPARQL_PASSWORD: ${{ secrets.SPARQL_PASSWORD }}
    steps:
    - uses: actions/checkout@v7
    - name: Stop current Prez if exists
      run: |
        if [ -d "/home/ubuntu/prez4/" ]; then
          cd /home/ubuntu/prez4/
          docker compose -f prez-compose.yaml stop prez4
        fi
    - name: Copy files
      run: |
        mkdir -p /home/ubuntu/prez4/
        cp -Rf prez-compose.yaml prez_config /home/ubuntu/prez4/
    - name: Deploy Prez
      working-directory: /home/ubuntu/prez4/
      run: docker compose -f prez-compose.yaml up -d
